# Generated by Django 4.2.6 on 2023-10-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.IntegerField()),
                ('falecido', models.BooleanField(default=False)),
                ('parentesco', models.CharField(choices=[('PO', 'Primo'), ('PA', 'Prima'), ('TIO', 'Tio'), ('TIA', 'Tia'), ('M', 'Mae'), ('P', 'Pai'), ('I', 'Irmao')], max_length=150)),
            ],
        ),
    ]
